[package]
name = "thinbasic_rusty"
version = "0.1.0"
authors = ["petrSchreiber <petrschreiber@gmail.com>"]

[dependencies.thinbasic]
path = "../thinbasic_core_sdk"

[lib]
name = "thinbasic_rusty"
crate-type = ["cdylib"]

